In [10]:
import numpy as np
import sys

### Numpy array vs Python lists

- Speed difference

In [7]:
a = [i for i in range(100000000)]
b = [i for i in range(100000000,200000000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
finish = time.time()
list_total_time = finish - start
print(f"Total Time took to Loop through list: {list_total_time}")


Total Time took to Loop through list: 7.945310831069946


In [8]:
a = np.arange(100000000)
b = np.arange(100000000,200000000)

import time 

start = time.time()

c = a + b

finish = time.time()
np_total_time = finish - start
print(f"Total Time took to Loop through numpy array: {np_total_time}")


Total Time took to Loop through numpy array: 0.49816298484802246


In [9]:
list_total_time/np_total_time

15.949219578194613

In [13]:
# memory
a = [i for i in range(10000000)]
import sys

list_memory = sys.getsizeof(a)
list_memory

89095160

In [27]:
b = np.arange(10000000, dtype=np.int64)
print(b.dtype)
np_memory = sys.getsizeof(b)
np_memory

int64


80000112

In [28]:
list_memory - np_memory

9095048

### Advance Indexing
*****************


In [30]:
# Normal Indexing and slicing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
a[1:2,:]

array([[4, 5, 6, 7]])

In [ ]:
## For fetching 4
a[1:2,0:1]

- Fancy Indexing


In [47]:
# Fancy Indexing
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
## Fetching specific rows
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [68]:
## Fetching specific Column

a[2:4,[0,1,3]]

array([[ 8,  9, 11],
       [12, 13, 15]])

- Boolean Indexing


In [71]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[26, 69, 45, 82],
       [42, 86, 47, 32],
       [35, 79, 23, 82],
       [15, 30, 97, 93],
       [80, 95, 37, 15],
       [96, 77,  1, 11]], dtype=int32)

In [72]:
# find all numbers greater than 50
a[a > 50]

array([69, 82, 86, 79, 82, 97, 93, 80, 95, 96, 77], dtype=int32)

In [73]:
# find out even numbers
a[a % 2 == 0]

array([26, 82, 42, 86, 32, 82, 30, 80, 96], dtype=int32)

In [74]:
# find all numbers greater than 50 and are even

a[(a > 50) & (a % 2 == 0)]

array([82, 86, 82, 80, 96], dtype=int32)

In [75]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([26, 69, 45, 82, 86, 47, 32, 79, 23, 82, 15, 30, 97, 93, 80, 95, 37,
       15, 96,  1, 11], dtype=int32)

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.