### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [1]:
import numpy as np

### 1. Techniques for creating numpy array

In [2]:
a = np.array([1,2,3])
print(type(a))
print(f"{a}\n\nThis is can be denoted as vector")

<class 'numpy.ndarray'>
[1 2 3]

This is can be denoted as vector


In [3]:
a = np.array([[1,2,3],[4,5,6]])
print(f"{a}\n\nThis is can be denoted as Matrix")

[[1 2 3]
 [4 5 6]]

This is can be denoted as Matrix


In [4]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f"{a}\n\nThis is can be denoted as Tensor")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

This is can be denoted as Tensor


- Float

In [5]:
a = np.array([
              [[1,2],[3,4]],
              [[5,6],[7,8]],
              [[9,10],[1,12]]
              ], dtype=float)
print(f"{a}\n\nThis is can be denoted as Tensor")

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [ 1. 12.]]]

This is can be denoted as Tensor


- Boolean

In [6]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]], dtype=bool)
print(f"{a}\n\nThis is can be denoted as Tensor")

[[[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]

This is can be denoted as Tensor


- Arange

In [7]:
arng = np.arange(1,10+1)
print(f"{arng}\n\nThis numpy array is created by using arrange method")

[ 1  2  3  4  5  6  7  8  9 10]

This numpy array is created by using arrange method


In [8]:
arng = arng.reshape(2,5)
arng

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### 2. Initialization Techniques

- np.once

In [9]:

np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

- np.zeros

In [10]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

- np.random.random

In [11]:
np.random.random((2,5))

array([[0.25269452, 0.18073978, 0.76223384, 0.13894904, 0.21967041],
       [0.34368055, 0.73647037, 0.75559404, 0.45745814, 0.03036446]])

- Linear Space (lower num, high num, number of points)

In [12]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

- Identity Matrix (Which diagnal items are Ones)

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 3. Array Attributes

In [14]:
a = np.array([
              [[1,2],[3,4]],
              [[5,6],[7,8]],
              [[9,10],[1,12]]
              ], dtype=float)
print(f"{a}\n\nThis is can be denoted as Tensor")

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [ 1. 12.]]]

This is can be denoted as Tensor


- ndim Dimension

In [15]:
print(f"It can be interpret that is has '{a.ndim}' Dimension")
a.ndim

It can be interpret that is has '3' Dimension


3

- shape

In [16]:
a.shape

(3, 2, 2)

In [17]:
x,y,z = a.shape
print(f"It can be interpret that is has '{x}' Dimensions with '{y}' column and '{z} row")
a.shape

It can be interpret that is has '3' Dimensions with '2' column and '2 row


(3, 2, 2)

- Size

In [18]:
print(f"It can be interpret that is has total '{a.size}' elemements")
a.size

It can be interpret that is has total '12' elemements


12

- Item Size

In [19]:
a = np.arange(1,5+1, dtype=np.int32)
print(f"It can interpret as np.int32 occupies '{a.itemsize}' in menory")
a.itemsize

It can interpret as np.int32 occupies '4' in menory


4

In [20]:
b = np.arange(1,5+1, dtype=np.int64)
print(f"It can interpret as np.int64 occupies '{b.itemsize}' in menory")
b.itemsize

It can interpret as np.int64 occupies '8' in menory


8

- dtype

In [21]:
print(a.dtype)
print(b.dtype)

int32
int64


- Changing Data type (astype)

In [58]:
a = np.array([
              [[1,2],[3,4]],
              [[5,6],[7,8]],
              [[9,10],[1,12]]
              ], dtype=float)
a

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [ 1., 12.]]])

In [59]:
a.astype(np.int64)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [ 1, 12]]])

### 4. Array Operation

In [63]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- Scaler Operation

In [64]:
a1*100

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [65]:
a2*1000

array([[12000, 13000, 14000, 15000],
       [16000, 17000, 18000, 19000],
       [20000, 21000, 22000, 23000]])

In [66]:
a1+100

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [67]:
a2>20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

- Vector Operation

In [81]:
a1.shape

(3, 4)

In [80]:
a2.shape

(3, 4)

In [74]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [29]:
a1 **2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [83]:
a1 **20

array([[                   0,                    1,              1048576,
                  3486784401],
       [       1099511627776,       95367431640625,     3656158440062976,
           79792266297612001],
       [ 1152921504606846976, -6289078614652622815,  7766279631452241920,
         8667208279016151025]])

### 5. Array Functions

- round

In [85]:
a1 = np.random.random((3,3))
a1

array([[0.18506076, 0.40823588, 0.19099865],
       [0.81322328, 0.30380588, 0.97248862],
       [0.97912054, 0.82315341, 0.58506698]])

In [86]:
aa = np.round(a1*100)
aa

array([[19., 41., 19.],
       [81., 30., 97.],
       [98., 82., 59.]])

- floor 
- closure to zero

In [114]:
np.random.seed(0)
test =np.random.random((2,3))
test


array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [118]:
np.floor(test)


array([[0., 0., 0.],
       [0., 0., 0.]])

- celing
- close to 1

In [119]:
np.ceil(test)

array([[1., 1., 1.],
       [1., 1., 1.]])

- axis = 1 (row)
- axis = 0 (column)

- Max

In [87]:
np.max(aa)

np.float64(98.0)

In [88]:
np.max(aa, axis=0)

array([98., 82., 97.])

In [89]:
np.max(aa,axis=1)

array([41., 97., 98.])

- Min

In [35]:
np.min(aa, axis=0)

array([ 7., 12., 49.])

In [36]:
np.min(aa, axis=1)

array([ 7., 36., 12.])

- Sum

In [37]:
np.sum(aa)

np.float64(483.0)

In [38]:
np.sum(aa, axis=0)

array([161., 113., 209.])

In [39]:
np.sum(aa, axis=1)

array([134., 226., 123.])

- Prod

In [40]:
np.prod(aa)

np.float64(333801670325760.0)

In [41]:
np.prod(aa, axis=0)

array([ 39928.,  28080., 297724.])

In [42]:
np.prod(aa, axis=1)

array([ 28210., 324576.,  36456.])

- Mean

In [43]:
np.mean(aa)

np.float64(53.666666666666664)

In [44]:
np.mean(aa, axis=0)

array([53.66666667, 37.66666667, 69.66666667])

In [45]:
np.mean(aa, axis=1)

array([44.66666667, 75.33333333, 41.        ])

- Median

In [46]:
np.median(aa)

np.float64(62.0)

In [47]:
np.median(aa, axis=0)

array([62., 36., 62.])

In [48]:
np.median(aa, axis=1)

array([62., 92., 49.])

- std

In [49]:
np.std(aa)

np.float64(29.720924166878348)

In [50]:
np.std(aa, axis=0)

array([35.19785347, 21.66923062, 20.72572208])

In [51]:
np.std(aa, axis=1)

array([26.66249967, 27.92052212, 21.18175315])

- Variance 

In [52]:
np.var(aa)

np.float64(883.3333333333334)

In [53]:
np.var(aa, axis=0)

array([1238.88888889,  469.55555556,  429.55555556])

In [54]:
np.var(aa, axis=1)

array([710.88888889, 779.55555556, 448.66666667])

- Dot Product

In [94]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [96]:
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

- log and exponent

In [98]:
np.log(a2)

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [99]:
np.exp(a2)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

### Indexing

In [145]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [146]:
a1[5]

np.int64(5)

In [147]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- for 2 D Matrix [row, column]

In [148]:
## Fetching 6 fro given Matix
a2[1,2]

np.int64(6)

In [149]:
## Fetching 11 fro given Matix
a2[2,3]

np.int64(11)

In [150]:
## Fetching 4 fro given Matix
a2[1,0]

np.int64(4)

- For 3D Matrix [matrix, row,column]

In [151]:
## Fetching 
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [156]:
## Fetching 3 from the tensor
a3[0,1,1]

np.int64(3)

In [159]:
## Fetching 5 from the tensor
a3[1,0,1]

np.int64(5)

### Slicing

In [160]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
a1[1:5]

array([1, 2, 3, 4])

In [165]:
### Slicing Operation for 2D metrics
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
a2[0:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [175]:
## Row Level fetching
a2[0,:]

array([0, 1, 2, 3])

In [177]:
## Column Level fetching
a2[:,0]

array([0, 4, 8])

In [190]:
## Fetching 5,6,9,10
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [200]:
## Fetching 0,3,8,11
a2[0::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [208]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [222]:
## Fetching 1,3,9,11
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [258]:
a2[1:2,:]

array([[4, 5, 6, 7]])

In [264]:
a2[:,0::3]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [254]:
a2[1:2,0::3]

array([[4, 7]])

In [268]:
### Slicing Operation for 2D metricsnp
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [289]:
a3[1:2,1:2,:]

array([[[12, 13, 14]]])

In [290]:
## 22, 23, 25 26

In [291]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [298]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [308]:
# 0, 2 , 18 , 20

a3[0::2, 0:1, 0::2]

array([[[ 0,  2]],

       [[18, 20]]])

### Iterating

In [309]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [321]:
## Array
for i in a1:
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,

In [322]:
## Matrix
for row in a2:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [323]:
## Tensor
for two_d_array in a3:
    print(two_d_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [324]:
## For all numpy
for i in np.nditer(a3):
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,

### Reshape

In [333]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [334]:
a2.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [335]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [342]:
a3.reshape(9,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

### Transpose

In [325]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [326]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [327]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Ravel 
- convert ndimension numpy array to One dimension array

In [340]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [347]:
## Horizontal Staking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [348]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [349]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [352]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [353]:
## Horizontal Staking

In [355]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Spliting

In [367]:
## Horizontal Split

a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [368]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [364]:
## Vertical Split
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [366]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]