### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [1]:
import numpy as np

### 1. Techniques for creating numpy array

In [2]:
a = np.array([1,2,3])
print(type(a))
print(f"{a}\n\nThis is can be denoted as vector")

<class 'numpy.ndarray'>
[1 2 3]

This is can be denoted as vector


In [3]:
a = np.array([[1,2,3],[4,5,6]])
print(f"{a}\n\nThis is can be denoted as Matrix")

[[1 2 3]
 [4 5 6]]

This is can be denoted as Matrix


In [4]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f"{a}\n\nThis is can be denoted as Tensor")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

This is can be denoted as Tensor


- Float

In [17]:
a = np.array([
              [[1,2],[3,4]],
              [[5,6],[7,8]],
              [[9,10],[1,12]]
              ], dtype=float)
print(f"{a}\n\nThis is can be denoted as Tensor")

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [ 1. 12.]]]

This is can be denoted as Tensor


- Boolean

In [6]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]], dtype=bool)
print(f"{a}\n\nThis is can be denoted as Tensor")

[[[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]

This is can be denoted as Tensor


- Arange

In [7]:
arng = np.arange(1,10+1)
print(f"{arng}\n\nThis numpy array is created by using arrange method")

[ 1  2  3  4  5  6  7  8  9 10]

This numpy array is created by using arrange method


In [8]:
arng = arng.reshape(2,5)
arng

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### 2. Initialization Techniques

- np.once

In [9]:

np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

- np.zeros

In [10]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

- np.random.random

In [12]:
np.random.random((2,5))

array([[0.07722822, 0.78275249, 0.56777076, 0.06355847, 0.81598213],
       [0.68004279, 0.9711068 , 0.22713048, 0.32421981, 0.33449398]])

- Linear Space (lower num, high num, number of points)

In [ ]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

- Identity Matrix (Which diagnal items are Ones)

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 3. Array Attributes

In [35]:
a = np.array([
              [[1,2],[3,4]],
              [[5,6],[7,8]],
              [[9,10],[1,12]]
              ], dtype=float)
print(f"{a}\n\nThis is can be denoted as Tensor")

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [ 1. 12.]]]

This is can be denoted as Tensor


- ndim Dimension

In [36]:
print(f"It can be interpret that is has '{a.ndim}' Dimension")
a.ndim

It can be interpret that is has '3' Dimension


3

- shape

In [37]:
a.shape

(3, 2, 2)

In [42]:
x,y,z = a.shape
print(f"It can be interpret that is has '{x}' Dimensions with '{y}' column and '{z} row")
a.shape

It can be interpret that is has '3' Dimensions with '2' column and '2 row


(3, 2, 2)

- Size

In [45]:
print(f"It can be interpret that is has total '{a.size}' elemements")
a.size

It can be interpret that is has total '12' elemements


12

- Item Size

In [55]:
a = np.arange(1,5+1, dtype=np.int32)
print(f"It can interpret as np.int32 occupies '{a.itemsize}' in menory")
a.itemsize

It can interpret as np.int32 occupies '4' in menory


4

In [57]:
b = np.arange(1,5+1, dtype=np.int64)
print(f"It can interpret as np.int64 occupies '{b.itemsize}' in menory")
b.itemsize

It can interpret as np.int64 occupies '8' in menory


8

- dtype

In [61]:
print(a.dtype)
print(b.dtype)

int32
int64


- Changing Data type (astype)

In [67]:
a = np.array([
              [[1,2],[3,4]],
              [[5,6],[7,8]],
              [[9,10],[1,12]]
              ], dtype=float)
a.astype(np.int64)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [ 1, 12]]])

### 4. Array Operation

In [74]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- Scaler Operation

In [78]:
a1*100

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [79]:
a2*1000

array([[12000, 13000, 14000, 15000],
       [16000, 17000, 18000, 19000],
       [20000, 21000, 22000, 23000]])

In [81]:
a1+100

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [85]:
a2>20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

- Vector Operation

In [86]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [87]:
a1 **2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

### 5. Array Functions

In [117]:
a1 = np.random.random((3,3))
np.round(a1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 1., 0.]])

In [118]:
aa = np.round(a1*100)
aa

array([[23., 87., 33.],
       [17., 12., 59.],
       [53., 65., 39.]])

- axis = 1 (row)
- axis = 0 (column)

- Max

In [120]:
np.max(aa)

np.float64(87.0)

In [122]:
np.max(aa, axis=0)

array([53., 87., 59.])

In [123]:
np.max(aa,axis=1)

array([87., 59., 65.])

- Min

In [125]:
np.min(aa, axis=0)

array([17., 12., 33.])

In [126]:
np.min(aa, axis=1)

array([23., 12., 39.])

- Sum

In [130]:
np.sum(aa)

np.float64(388.0)

In [128]:
np.sum(aa, axis=0)

array([ 93., 164., 131.])

In [129]:
np.sum(aa, axis=1)

array([143.,  88., 157.])

- Prod

In [131]:
np.prod(aa)

np.float64(106781751673740.0)

In [132]:
np.prod(aa, axis=0)

array([20723., 67860., 75933.])

In [133]:
np.prod(aa, axis=1)

array([ 66033.,  12036., 134355.])

- Mean

In [134]:
np.mean(aa)

np.float64(43.111111111111114)

In [135]:
np.mean(aa, axis=0)

array([31.        , 54.66666667, 43.66666667])

In [136]:
np.mean(aa, axis=1)

array([47.66666667, 29.33333333, 52.33333333])

- Median

In [137]:
np.median(aa)

np.float64(39.0)

In [138]:
np.median(aa, axis=0)

array([23., 65., 39.])

In [139]:
np.median(aa, axis=1)

array([33., 17., 53.])

- std

In [140]:
np.std(aa)

np.float64(23.402015318934698)

In [141]:
np.std(aa, axis=0)

array([15.74801575, 31.47838765, 11.11555467])

In [142]:
np.std(aa, axis=1)

array([28.11089152, 21.07657995, 10.6249183 ])

- Variance 

In [143]:
np.var(aa)

np.float64(547.6543209876543)

In [144]:
np.var(aa, axis=0)

array([248.        , 990.88888889, 123.55555556])

In [145]:
np.var(aa, axis=1)

array([790.22222222, 444.22222222, 112.88888889])

- Dot Product

In [148]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [149]:
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])