In [20]:
import numpy as np

- axis = 1 -> row
- axis = 0 -> column

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [32]:
# code
import numpy as np
a = np.random.randint(1,100,15)
print(a)
print(np.sort(a))
print(np.sort(a)[::-1]) ## Desending order or reverse

[59 32  2 66 42 58 36 12 47 83 92  1 15 54 13]
[ 1  2 12 13 15 32 36 42 47 54 58 59 66 83 92]
[92 83 66 59 58 54 47 42 36 32 15 13 12  2  1]


In [24]:
np.random.seed(0)

In [28]:

b = np.random.randint(1,100,24).reshape(6,4)
print(b)


[[73 10 21 81]
 [70 80 48 65]
 [83 89 50 30]
 [20 20 15 40]
 [33 66 10 58]
 [33 32 75 24]]


In [29]:
## row Level Sorting
print(np.sort(b, axis=1))

[[10 21 73 81]
 [48 65 70 80]
 [30 50 83 89]
 [15 20 20 40]
 [10 33 58 66]
 [24 32 33 75]]


In [30]:
## column Level Sorting
print(np.sort(b, axis=0))

[[20 10 10 24]
 [33 20 15 30]
 [33 32 21 40]
 [70 66 48 58]
 [73 80 50 65]
 [83 89 75 81]]


### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [34]:
# code
np.append(a,20000)

array([   59,    32,     2,    66,    42,    58,    36,    12,    47,
          83,    92,     1,    15,    54,    13, 20000])

In [37]:
b

array([[73, 10, 21, 81],
       [70, 80, 48, 65],
       [83, 89, 50, 30],
       [20, 20, 15, 40],
       [33, 66, 10, 58],
       [33, 32, 75, 24]], dtype=int32)

In [41]:
b.shape[0],1

(6, 1)

In [46]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[73., 10., 21., 81.,  1.],
       [70., 80., 48., 65.,  1.],
       [83., 89., 50., 30.,  1.],
       [20., 20., 15., 40.,  1.],
       [33., 66., 10., 58.,  1.],
       [33., 32., 75., 24.,  1.]])

In [49]:
np.append(b,np.zeros((b.shape[0],1)),axis=1)

array([[73., 10., 21., 81.,  0.],
       [70., 80., 48., 65.,  0.],
       [83., 89., 50., 30.,  0.],
       [20., 20., 15., 40.,  0.],
       [33., 66., 10., 58.,  0.],
       [33., 32., 75., 24.,  0.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [50]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [51]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [54]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
print(e)
print(np.unique(e))

[1 1 2 2 3 3 4 4 5 5 6 6]
[1 2 3 4 5 6]


### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [61]:
# code
a.shape

(15,)

In [63]:
a

array([59, 32,  2, 66, 42, 58, 36, 12, 47, 83, 92,  1, 15, 54, 13],
      dtype=int32)

In [64]:
np.expand_dims(a,axis=0)


array([[59, 32,  2, 66, 42, 58, 36, 12, 47, 83, 92,  1, 15, 54, 13]],
      dtype=int32)

In [65]:
np.expand_dims(a,axis=1)

array([[59],
       [32],
       [ 2],
       [66],
       [42],
       [58],
       [36],
       [12],
       [47],
       [83],
       [92],
       [ 1],
       [15],
       [54],
       [13]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [66]:
a

array([59, 32,  2, 66, 42, 58, 36, 12, 47, 83, 92,  1, 15, 54, 13],
      dtype=int32)

In [67]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  3,  5,  9, 10, 13]),)

In [71]:
# replace all values > 50 with 0
np.where(a>50,100,a)

array([100,  32,   2, 100,  42, 100,  36,  12,  47, 100, 100,   1,  15,
       100,  13], dtype=int32)

### np.argmax

The numpy.argmax() function returns index of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [69]:
a

array([59, 32,  2, 66, 42, 58, 36, 12, 47, 83, 92,  1, 15, 54, 13],
      dtype=int32)

In [70]:
np.argmax(a)

np.int64(10)

In [72]:
a[10]

np.int32(92)

### np.argmin

The numpy.argmax() function returns index of the min element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [74]:
np.argmin(a)

np.int64(11)

In [75]:
a[11]

np.int32(1)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [76]:
a

array([59, 32,  2, 66, 42, 58, 36, 12, 47, 83, 92,  1, 15, 54, 13],
      dtype=int32)

In [77]:
np.cumsum(a)

array([ 59,  91,  93, 159, 201, 259, 295, 307, 354, 437, 529, 530, 545,
       599, 612])

In [78]:
b

array([[73, 10, 21, 81],
       [70, 80, 48, 65],
       [83, 89, 50, 30],
       [20, 20, 15, 40],
       [33, 66, 10, 58],
       [33, 32, 75, 24]], dtype=int32)

In [79]:
## Row Level 
np.cumsum(b,axis=1)

array([[ 73,  83, 104, 185],
       [ 70, 150, 198, 263],
       [ 83, 172, 222, 252],
       [ 20,  40,  55,  95],
       [ 33,  99, 109, 167],
       [ 33,  65, 140, 164]])

In [81]:
## Column Level 
np.cumsum(b,axis=0)

array([[ 73,  10,  21,  81],
       [143,  90,  69, 146],
       [226, 179, 119, 176],
       [246, 199, 134, 216],
       [279, 265, 144, 274],
       [312, 297, 219, 298]])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [83]:
a

array([59, 32,  2, 66, 42, 58, 36, 12, 47, 83, 92,  1, 15, 54, 13],
      dtype=int32)

In [85]:
np.percentile(a,100)

np.float64(92.0)

In [86]:
np.percentile(a,0)

np.float64(1.0)

In [88]:
np.percentile(a,50)

np.float64(42.0)

In [89]:
np.median(a)

np.float64(42.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [90]:
# code
a

array([59, 32,  2, 66, 42, 58, 36, 12, 47, 83, 92,  1, 15, 54, 13],
      dtype=int32)

In [91]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))